select jsonb_build_object(
  'types', (select coalesce(jsonb_agg(jsonb_build_object('schema',n.nspname,'name',t.typname,'kind',t.typtype,'base_type',format_type(t.typbasetype,t.typtypmod),'not_null',t.typnotnull,'default',t.typdefault)), '[]') from pg_type t join pg_namespace n on n.oid=t.typnamespace where n.nspname not like 'pg_%' and n.nspname <> 'information_schema' and t.typtype in ('d','e','r','m') and t.typelem=0),
  'event_triggers', (select coalesce(jsonb_agg(jsonb_build_object('name',e.evtname,'event',e.evtevent,'enabled',e.evtenabled,'function',e.evtfoid::regprocedure::text,'tags',e.evttags)), '[]') from pg_event_trigger e),
  'function_permissions', (select coalesce(jsonb_agg(jsonb_build_object('function',p.oid::regprocedure::text,'anon_execute',has_function_privilege('anon',p.oid,'EXECUTE'),'authenticated_execute',has_function_privilege('authenticated',p.oid,'EXECUTE'),'service_role_execute',has_function_privilege('service_role',p.oid,'EXECUTE'))), '[]') from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.prokind in ('f','p')),
  'table_permissions', (select coalesce(jsonb_agg(jsonb_build_object('schema',n.nspname,'table',c.relname,'anon_select',has_table_privilege('anon',c.oid,'SELECT'),'authenticated_select',has_table_privilege('authenticated',c.oid,'SELECT'),'anon_insert',has_table_privilege('anon',c.oid,'INSERT'),'anon_update',has_table_privilege('anon',c.oid,'UPDATE'),'anon_delete',has_table_privilege('anon',c.oid,'DELETE'))), '[]') from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind in ('r','p','v','m')),
  'sequence_ownership', (select coalesce(jsonb_agg(jsonb_build_object('sequence',s.oid::regclass::text,'table',c.oid::regclass::text,'column',a.attname,'dependency_type',d.deptype)), '[]') from pg_class s join pg_depend d on d.objid=s.oid and d.classid='pg_class'::regclass join pg_class c on c.oid=d.refobjid join pg_attribute a on a.attrelid=c.oid and a.attnum=d.refobjsubid where s.relkind='S' and d.deptype in ('a','i')),
  'publications', (select coalesce(jsonb_agg(jsonb_build_object('name',p.pubname,'all_tables',p.puballtables,'insert',p.pubinsert,'update',p.pubupdate,'delete',p.pubdelete,'truncate',p.pubtruncate)), '[]') from pg_publication p),
  'replication_tables', (select coalesce(jsonb_agg(to_jsonb(t)), '[]') from pg_publication_tables t),
  'storage_object_counts', (select coalesce(jsonb_agg(jsonb_build_object('bucket_id',b.id,'objects',(select count(*) from storage.objects o where o.bucket_id=b.id))), '[]') from storage.buckets b),
  'vault_secret_count', (select count(*) from vault.secrets)
) as catalog_extra;
