-- Auditoría de esquema: solo SELECT, sin datos de clientes ni contenido de Vault/Storage.
select jsonb_build_object(
  'captured_at', now(),
  'schemas', (select coalesce(jsonb_agg(jsonb_build_object('name', nspname, 'owner', pg_get_userbyid(nspowner), 'acl', nspacl::text)), '[]') from pg_namespace where nspname not like 'pg_%' and nspname <> 'information_schema'),
  'tables', (select coalesce(jsonb_agg(jsonb_build_object('schema', n.nspname, 'name', c.relname, 'kind', c.relkind, 'owner', pg_get_userbyid(c.relowner), 'rls', c.relrowsecurity, 'force_rls', c.relforcerowsecurity, 'acl', c.relacl::text, 'estimated_rows', c.reltuples)), '[]') from pg_class c join pg_namespace n on n.oid=c.relnamespace where c.relkind in ('r','p','v','m','f') and n.nspname not like 'pg_%' and n.nspname <> 'information_schema'),
  'columns', (select coalesce(jsonb_agg(jsonb_build_object('schema', n.nspname, 'table', c.relname, 'name', a.attname, 'position', a.attnum, 'type', format_type(a.atttypid,a.atttypmod), 'not_null', a.attnotnull, 'default', pg_get_expr(d.adbin,d.adrelid), 'identity', a.attidentity, 'generated', a.attgenerated)), '[]') from pg_attribute a join pg_class c on c.oid=a.attrelid join pg_namespace n on n.oid=c.relnamespace left join pg_attrdef d on d.adrelid=a.attrelid and d.adnum=a.attnum where a.attnum>0 and not a.attisdropped and c.relkind in ('r','p','v','m','f') and n.nspname not like 'pg_%' and n.nspname <> 'information_schema'),
  'constraints', (select coalesce(jsonb_agg(jsonb_build_object('schema', n.nspname, 'table', c.relname, 'name', con.conname, 'type', con.contype, 'definition', pg_get_constraintdef(con.oid,true), 'validated', con.convalidated)), '[]') from pg_constraint con join pg_class c on c.oid=con.conrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname not like 'pg_%' and n.nspname <> 'information_schema'),
  'indexes', (select coalesce(jsonb_agg(to_jsonb(i)), '[]') from pg_indexes i where schemaname not like 'pg_%' and schemaname <> 'information_schema'),
  'enums', (select coalesce(jsonb_agg(jsonb_build_object('schema', n.nspname,'name', t.typname,'label', e.enumlabel,'position', e.enumsortorder)), '[]') from pg_type t join pg_namespace n on n.oid=t.typnamespace join pg_enum e on e.enumtypid=t.oid),
  'views', (select coalesce(jsonb_agg(jsonb_build_object('schema', n.nspname,'name', c.relname,'kind',c.relkind,'definition',pg_get_viewdef(c.oid,true))), '[]') from pg_class c join pg_namespace n on n.oid=c.relnamespace where c.relkind in ('v','m') and n.nspname in ('public','storage','cron','vault')),
  'functions', (select coalesce(jsonb_agg(jsonb_build_object('schema', n.nspname,'name', p.proname,'identity', pg_get_function_identity_arguments(p.oid),'arguments',pg_get_function_arguments(p.oid),'result',pg_get_function_result(p.oid),'language',l.lanname,'owner',pg_get_userbyid(p.proowner),'security_definer',p.prosecdef,'volatility',p.provolatile,'config',p.proconfig,'acl',p.proacl::text,'definition',case when n.nspname='public' then pg_get_functiondef(p.oid) else null end)), '[]') from pg_proc p join pg_namespace n on n.oid=p.pronamespace join pg_language l on l.oid=p.prolang where p.prokind in ('f','p') and n.nspname not like 'pg_%' and n.nspname <> 'information_schema'),
  'triggers', (select coalesce(jsonb_agg(jsonb_build_object('schema', n.nspname,'table',c.relname,'name',t.tgname,'enabled',t.tgenabled,'definition',pg_get_triggerdef(t.oid,true))), '[]') from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where not t.tgisinternal and n.nspname not like 'pg_%'),
  'policies', (select coalesce(jsonb_agg(to_jsonb(p)), '[]') from pg_policies p),
  'table_grants', (select coalesce(jsonb_agg(to_jsonb(g)), '[]') from information_schema.role_table_grants g where table_schema not like 'pg_%' and table_schema <> 'information_schema'),
  'column_grants', (select coalesce(jsonb_agg(to_jsonb(g)), '[]') from information_schema.role_column_grants g where table_schema in ('public','storage')),
  'default_acl', (select coalesce(jsonb_agg(jsonb_build_object('role',pg_get_userbyid(d.defaclrole),'schema',n.nspname,'type',d.defaclobjtype,'acl',d.defaclacl::text)), '[]') from pg_default_acl d left join pg_namespace n on n.oid=d.defaclnamespace),
  'sequences', (select coalesce(jsonb_agg(jsonb_build_object('schema',s.schemaname,'name',s.sequencename,'owner',s.sequenceowner,'type',s.data_type,'start',s.start_value::text,'min',s.min_value::text,'max',s.max_value::text,'increment',s.increment_by::text,'cycle',s.cycle)), '[]') from pg_sequences s where schemaname not like 'pg_%'),
  'extensions', (select coalesce(jsonb_agg(jsonb_build_object('name',e.extname,'version',e.extversion,'schema',n.nspname)), '[]') from pg_extension e join pg_namespace n on n.oid=e.extnamespace),
  'buckets', (select coalesce(jsonb_agg(jsonb_build_object('id',b.id,'name',b.name,'public',b.public,'file_size_limit',b.file_size_limit,'allowed_mime_types',b.allowed_mime_types)), '[]') from storage.buckets b),
  'migration_history', (select coalesce(jsonb_agg(jsonb_build_object('version',m.version,'name',m.name)), '[]') from supabase_migrations.schema_migrations m),
  'optional_services', jsonb_build_object('cron_jobs_table', to_regclass('cron.job') is not null,'vault_secrets_table',to_regclass('vault.secrets') is not null)
) as catalog;
